name: Feature Request
description: Request a new feature
labels: [feature-request, needs-triage]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Short description of the feature you are proposing.
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: |
        Why do you need this feature?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: |
        Please include prototype/workaround/sketch/reference implementation.
    validations:
      required: false

  - type: textarea
    id: other
    attributes:
      label: Other Info
      description: |
        Add any additional information about the issue
    validations:
      required: false

  - type: checkboxes
    id: acknowledgments
    attributes:
      label: Acknowledge
      options:
        - label: I may be able to implement this feature request
          required: false
        - label: This feature might incur a breaking change
          required: false
